name: asicity
description: Aplicativo AsiCity - Ouvidoria urbana em tempo real
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # ðŸ”¥ FIREBASE
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_messaging: ^15.2.10

  # ðŸ“ MAPAS
  google_maps_flutter: ^2.6.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  url_launcher: ^6.2.5

  # ðŸ“¸ IMAGEM
  image_picker: ^1.0.7

  # ðŸŽ¨ UI
  google_fonts: ^6.1.0

  # ðŸ§  UTILIDADES
  provider: ^6.1.2
  intl: ^0.19.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true